Endringer på encrypt-post endepunkt og kryptering
kartverket/backstage-plugin-risk-crypto-service pull request #8
Opened 2024-07-25 13:11 UTC by ostenedvardsen

Manuell url-enkoding av plaintext før og etter sending har blitt fjernet i post-endepunktet, da dette håndteres av at plaintexten ligger i en post body. 

Kodesnutten som fjerner "path_regex"-linja i config har blitt flyttet fra backstage-plugin-risk-scorecard-backend til crypto-service. Tidligere ble det lagret to versjoner av .sops.yaml i repoene: en med og en uten <path_regex: '\.risc\.yaml$'>, ettersom en visual studio code plugin trenger den, og sops trenger at den fjernes. På et tidspunkt har dette blitt gjort om til at linja fjernes i backend før kryptering. Dette har blitt flyttet til crypto-service for å forsikre at configen er på rett format før enkryptering. 

Opprettet og flyttet på noen relevante datatyper.

2024-07-26 11:15 UTC, frikkha commented on src/main/kotlin/crypto_service/service/EncryptionService.kt
> +            print(e.message)
`logger` 🤓 
I #7 har jeg lagt til en logger, du kan ta en titt der for hvordan man instansierer loggeren!

2024-07-26 11:56 UTC, frikkha commented on src/main/kotlin/crypto_service/exception/SopsEncryptionException.kt
Var det meningen å slette denne? Eventuelt om den skulle bli flyttet til en annen folder, ettersom det i lagt til `import crypto_service.exception.exceptions.SopsEncryptionException` i `GlobalExceptionHandler.kt`.

2024-07-26 11:58 UTC, frikkha commented on src/main/kotlin/crypto_service/controller/CryptoController.kt
> +import crypto_service.controller.models.EncryptionRequest
Mangler denne?

2024-07-26 11:58 UTC, frikkha commented on src/main/kotlin/crypto_service/controller/CryptoController.kt
> +        _config: String,
rename denne til `config`?

2024-07-26 11:59 UTC, frikkha requested changes
Er et par ting jeg mistenker at ikke er blitt comittet 🧐 Ellers ser det bra ut!

2024-07-26 12:21 UTC, frikkha commented on src/main/kotlin/crypto_service/controller/CryptoController.kt
>      @PostMapping("/encryptPost")
Generelt spørsmål, trenger vi å kalle endepunktet for encrypt**Post**? Holder det at endepunktet heter `encrypt` og at det er av typen `Post`?

2024-07-29 08:35 UTC, frikkha approved these changes
<img src="https://media3.giphy.com/media/mGK1g88HZRa2FlKGbz/giphy.gif"/>

2024-07-29 11:05 UTC, ttessem approved these changes

2024-07-29 11:05 UTC, merged